#   # Visual Studio code
#   vscode:
#     container_name: vscode
#     image: codercom/code-server:latest
#     volumes:
#       # Set <project dir> to the directory you want to open in VS Code.
#       - /var/lib/docker/volumes/ha/config:/home/coder/project
#       # <vs code config> should point to a local dir where vs code stores its data.
#       - /var/lib/docker/volumes/vscode/config:/home/coder/.local/share/code-server
#     ports:
#       - "8443:8443"
#     command: code-server --auth password --port 8443 --disable-telemetry /home/coder/project
#     environment:
#       - PUID=1000
#       - PGID=1000
#       - TZ=Europe/Amsterdam
# #       - PASSWORD= "klmklm"
#     restart: unless-stopped
    
---
version: "2.1"
services:
  code-server:
    image: ghcr.io/linuxserver/code-server
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - PASSWORD=klmklm #optional
#       - HASHED_PASSWORD= #optional
#       - SUDO_PASSWORD=password #optional
#       - SUDO_PASSWORD_HASH= #optional
#       - PROXY_DOMAIN=code-server.my.domain #optional
    volumes:
      - /var/lib/docker/volumes/ha/config:/home/coder/project
      - /var/lib/docker/volumes/vscode/config:/home/coder/.local/share/code-server
    ports:
      - 8443:8443
    restart: unless-stopped
