# Docker Compose Yaml 
version: "2.4"
services:
    node-red:
        image: nodered/node-red:latest
        container_name: my-node-red
        restart: always
        ports:
            - 1881:1880
        volumes:
             - /var/lib/docker/volumes/node-red/data:/data
